### Question 1: Create an element-wise comparison (greater, greater_equal, less and less_equal) of two given arrays.

In [40]:
import numpy as np
a = np.array([45,34,23,48,78,57])
b = np.array([59,23,33,109,87,91])
print("1st Array of numbers: ", a)
print("2nd Array of numbers: ", b)
print("Comparison to check 'greater than' between two arrays: ", np.greater(a, b))
print("Comparison to check 'greater_equal' between two arrays: ", np.greater_equal(a, b))
print("Comparison to check 'less than' between two arrays: ", np.less(a, b))
print("Comparison to check 'less_equal' between two arrays: ", np.less_equal(a, b))

1st Array of numbers:  [45 34 23 48 78 57]
2nd Array of numbers:  [ 59  23  33 109  87  91]
Comparison to check 'greater than' between two arrays:  [False  True False False False False]
Comparison to check 'greater_equal' between two arrays:  [False  True False False False False]
Comparison to check 'less than' between two arrays:  [ True False  True  True  True  True]
Comparison to check 'less_equal' between two arrays:  [ True False  True  True  True  True]


### Question 2: Write a NumPy program to create an array of 10 zeros,10 ones, 10 fives

In [7]:
import numpy as np
c=np.zeros(10)
print("An array of 10 zeros: ", c)
d=np.ones(10)
print("An array of 10 ones: ", d)
e=np.ones(10)*5
print("An array of 10 fives: ", e)

An array of 10 zeros:  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
An array of 10 ones:  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
An array of 10 fives:  [5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


### Question 3: Write a NumPy program to compute sum of all elements, sum of each column and sum of each row of a given array.

In [10]:
import numpy as np
f = np.array([[765,342,985,456],[658,856,395,957],[7453,843,9364,4364]])
print("Array of numbers: \n", f)
print("Sum of all elements: ", np.sum(f))
print("Sum of each column: ", np.sum(f, axis=0))
print("Sum of each row: ", np.sum(f, axis=1))

Array of numbers: 
 [[ 765  342  985  456]
 [ 658  856  395  957]
 [7453  843 9364 4364]]
Sum of all elements:  27438
Sum of each column:  [ 8876  2041 10744  5777]
Sum of each row:  [ 2548  2866 22024]


### Question 4: Write a NumPy program to add, subtract, multiply, divide arguments element-wise.

In [12]:
import numpy as np
g = np.array([[765,342,985,456],[658,856,395,957],[7453,843,9364,4364]])
print("Addition of two arrays: \n", np.add(f, g))
print("Subtraction of two arrays: \n", np.subtract(f, g))
print("Multiplicaition of two arrays: \n", np.multiply(f, g))
print("Division of two arrays: \n", np.divide(f, g))

Addition of two arrays: 
 [[ 1530   684  1970   912]
 [ 1316  1712   790  1914]
 [14906  1686 18728  8728]]
Subtraction of two arrays: 
 [[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
Multiplicaition of two arrays: 
 [[  585225   116964   970225   207936]
 [  432964   732736   156025   915849]
 [55547209   710649 87684496 19044496]]
Division of two arrays: 
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


### Question 5: Write a NumPy program to compute the trigonometric sine, cosine and tangent array of angles given in degree.

In [14]:
import numpy as np
print("sine of angles in array given in degrees: ", np.sin(np.array(a) * np.pi / 180.))
print("cosine of angles in array given in degrees: ", np.cos(np.array(a) * np.pi / 180.))
print("tangent of angles in array given in degrees: ", np.tan(np.array(a) * np.pi / 180.))

sine of angles in array given in degrees:  [0.70710678 0.5591929  0.39073113 0.74314483 0.9781476  0.83867057]
cosine of angles in array given in degrees:  [0.70710678 0.82903757 0.92050485 0.66913061 0.20791169 0.54463904]
tangent of angles in array given in degrees:  [1.         0.67450852 0.42447482 1.11061251 4.70463011 1.53986496]


### Question 6: Write a Pandas program to create and display a DataFrame from a specified dictionary data which has the index labels.

In [24]:
import pandas as pd
import numpy as np

marks = {'Names': ['Somu', 'Kiku', 'Amol', 'Lini', 'Ram'], 'Physics': [68, 74, 77, 78, 87], 'Chemistry': [84, 56, 73, 69, 91], 'Algebra': [78, 88, 82, 87, 97]}
sl_no = ['1', '2', '3', '4', '5']

h = pd.DataFrame(marks , index=sl_no)
print(h)

  Names  Physics  Chemistry  Algebra
1  Somu       68         84       78
2  Kiku       74         56       88
3  Amol       77         73       82
4  Lini       78         69       87
5   Ram       87         91       97


### Question 7: Write a Pandas program to select the 'name' and 'score' columns from the following DataFrame.

In [30]:
import pandas as pd
import numpy as np

marks1 = {'Names': ['Somu', 'Kiku', 'Amol', 'Lini', 'Ram'], 'Physics': [68, 74, 77, 78, 87], 'Chemistry': [84, 56, 73, 69, 91], 'Algebra': [78, 88, 82, 87, 97], 'Total Score': [230, 224, 232, 234, 275]}
sl_no = ['1', '2', '3', '4', '5']

h = pd.DataFrame(marks1 , index=sl_no)
print("Required columns: \n", h[['Names', 'Total Score']])

Required columns: 
   Names  Total Score
1  Somu          230
2  Kiku          224
3  Amol          232
4  Lini          234
5   Ram          275


### Question 8: Write a Pandas program to join the two given dataframes along rows and assign all data.

In [38]:
import pandas as pd
import numpy as np

marks1 = pd.DataFrame({'Names': ['Somu', 'Kiku', 'Amol', 'Lini', 'Ram'], 'Physics': [68, 74, 77, 78, 87], 'Chemistry': [84, 56, 73, 69, 91], 'Algebra': [78, 88, 82, 87, 97], 'Total Score': [230, 224, 232, 234, 275]})

marks2 = pd.DataFrame({'Names': ['Tinku', 'Miku', 'Shymol', 'Ani', 'Lal'], 'Physics': [68, 74, 77, 78, 87], 'Chemistry': [84, 56, 73, 69, 91], 'Algebra': [78, 88, 82, 87, 97], 'Total Score': [230, 224, 232, 234, 275]})

final_marks = pd.concat([marks1, marks2])
print("Joining the two given dataframes along rows: \n", final_marks)

Joining the two given dataframes along rows: 
     Names  Physics  Chemistry  Algebra  Total Score
0    Somu       68         84       78          230
1    Kiku       74         56       88          224
2    Amol       77         73       82          232
3    Lini       78         69       87          234
4     Ram       87         91       97          275
0   Tinku       68         84       78          230
1    Miku       74         56       88          224
2  Shymol       77         73       82          232
3     Ani       78         69       87          234
4     Lal       87         91       97          275


### Question 9: Write a Pandas program to detect missing values of a given DataFrame. Display True or False.

In [37]:
import pandas as pd
import numpy as np

marks3 = pd.DataFrame({'Names': ['Somu', 'Kiku', 'Amol', 'Lini', 'Ram'], 'Physics': [68, np.nan, 77, 78, 87], 'Chemistry': [84, 56, np.nan, 69, 91], 'Algebra': [78, 88, 82, np.nan, 97], 'Total Score': [230, 224, 232, np.nan, 275]})

marks4 = pd.DataFrame({'Names': ['Tinku', 'Miku', 'Shymol', 'Ani', 'Lal'], 'Physics': [68, 74, 77, np.nan, 87], 'Chemistry': [84, 56, 73, np.nan, 91], 'Algebra': [78, np.nan, 82, 87, 97], 'Total Score': [230, np.nan, 232, 234, 275]})

final_marks1 = pd.concat([marks3, marks4])
print("Missing values of the two given dataframes: \n", final_marks1.isna())

Missing values of the two given dataframes: 
    Names  Physics  Chemistry  Algebra  Total Score
0  False    False      False    False        False
1  False     True      False    False        False
2  False    False       True    False        False
3  False    False      False     True         True
4  False    False      False    False        False
0  False    False      False    False        False
1  False    False      False     True         True
2  False    False      False    False        False
3  False     True       True    False        False
4  False    False      False    False        False


### Question 10: Write a Pandas program to create and display a one-dimensional array-like object containing an array of data.

In [44]:
import pandas as pd
a1 = [45,34,23,48,78,57]
print("One-dimensional array-like object containing an array of data:\n", pd.Series(a))

One-dimensional array-like object containing an array of data:
 0    45
1    34
2    23
3    48
4    78
5    57
dtype: int32
